# Run model in docker container
log_level: INFO

# Model training parameters
train:
  model_name: wtnv_model
  num_train_epochs: 20
  per_device_train_batch_size: 24
  per_device_eval_batch_size: 32
  eval_steps: 400
  save_steps: 800
  warmup_steps: 500
